config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'

  resources :user, only: [:edit]
  resources :registered_applications

  namespace :api, defaults: { format: :json } do
    resources :events, only: [:create]
  end

  # Matches an HTTP options request, which is the CORS way of checking if
  # a cross domain request will be permitted, and calls the preflight method
  # in the EventsController.
  match 'api/events', to: 'api/events#preflight', via: [:options]
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :registered_application
end

app/models/registered_application.rb
class RegisteredApplication < ActiveRecord::Base
  belongs_to :user
  has_many :events

  validates :name, length: {minimum: 3, maximum: 30}, presence: true, uniqueness: true
  validates :url, length: {minimum: 3}, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :registered_applications
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: true, length: { minimum: 3, maximum: 30 }, uniqueness: true
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_filter :set_access_control_headers

  # Set CORS response headers. Permits POST requests across all domains.
  def set_access_control_headers
    # Permits requests from any origin
    headers['Access-Control-Allow-Origin'] = '*'

    # Permits POST, GET, and OPTIONS methods
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'

    # Permits HTTP header Content-Type, which is used by HTTP requests to
    # declare the type of data being sent.
    headers['Access-Control-Allow-Headers'] = 'Content-Type'
  end

  def create
    registered_application = RegisteredApplication.find_by(url: request.env['HTTP_ORIGIN'])

    if registered_application
      @event = Event.new(event_params)
      @event.registered_application = registered_application

      @event.save ? render(json: @event, status: :created) : render(json: {errors: @event.errors}, status: :unprocessable_entity)
    else
      render json: "Unregistered application", status: :unprocessable_entity
    end
  end

  # Returns a 200 status in response to a an HTTP options request
  def preflight
    head 200
  end

  private

  def event_params
    params.require(:event).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
  before_action :authenticate_user!

  def show
    @app = RegisteredApplication.find(params[:id])
    @user = User.find(current_user.id)
    @events = @app.events.group_by(&:name)
  end

  def index
    @apps = RegisteredApplication.where("user_id = ?", current_user.id)
    @user = User.find(current_user.id)
  end

  def new
    @app = RegisteredApplication.new
  end

  def create
    @app = RegisteredApplication.new(app_params)
    @app.user = current_user

    if @app.save
      flash[:notice] = "Registered new application."
      redirect_to @app
    else
      flash.now[:alert] = "There was an error registering the app."
      render :new
    end
  end

  def edit
    @app = RegisteredApplication.find(params[:id])
  end

  def update
    @app = RegisteredApplication.find(params[:id])
    @app.assign_attributes(app_params)

    if @app.save
      flash[:notice] = "#{@app.name} was updated successfully."
      redirect_to registered_application_path(@app)
    else
      flash.now[:alert] = "There was an error updating the app."
      render :edit
    end
  end

  def destroy
    @app = RegisteredApplication.find(params[:id])

    if @app.destroy
      flash[:notice] = "#{@app.name} was unregistered successfully."
      redirect_to registered_applications_path
    else
      flash.now[:notice] = "There was an error unregistering the app."
      render :index
    end
  end

  private

  def app_params
    params.require(:registered_application).permit(:name, :url)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user_name
    current_user.email.split("@").first
  end
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
  def event_summary(events)
    acc = {}
    events.each { |e| acc[e.name] ? acc[e.name] += 1 : acc[e.name] = 1 }
    acc
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmetrics</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", root_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to "My Apps", registered_applications_path %></li>
      <% end %>

      <div class="pull-right user-info">
        <% if user_signed_in? %>
          <%= link_to current_user.username, edit_user_registration_path, class: 'navbar-link' %>
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: 'navbar-link' %>
        <% else %>
          <%= link_to "Sign in", new_user_session_path, class: 'navbar-link' %>
          <%= link_to "Sign up", new_user_registration_path, class: 'navbar-link' %>
        <% end %>
      </div>
    </ul>
  </div>
  <div class="container">
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>

  </div>
</body>
</html>

app/views/registered_applications/_form.html.erb
<% if @app.errors.any? %>
  <% @app.errors.full_messages.each do |error_message| %>
    <%= error_message if @app.errors.full_messages.first == error_message %> <br />
  <% end %>
<% end %>
<%= form_for app do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: "Enter app name", autofocus: true %>
  </div>
  <div class="form-group">
    <%= f.label :url %>
    <%= f.text_field :url, class: 'form-control', placeholder: "Enter app url" %>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
    <%= link_to "Cancel", cancel_path, class: 'btn btn-danger' %>
  </div>
<% end %>

app/views/registered_applications/edit.html.erb
<div class="container">
  <div class="col-md-3"> </div>
  <div class="col-md-6">
    <h1>Edit <%= @app.name %></h1>
    <%= render partial: 'form', locals: {app: @app, cancel_path: registered_applications_path} %>
  </div>
</div>

app/views/registered_applications/index.html.erb
<h1>My Apps</h1>

<div class="row">
  <div class="col-md-4">
    <h3><%= @user.username %></h3>
    <h3><small>Apps: <%= @apps.count %></small></h3>
    <%= link_to "Register New App", new_registered_application_path, class: 'btn btn-success' %>
  </div>
  <div class="col-md-8">
    <table class="table table-hover">
      <thead>
        <tr>
          <th width="50%">App Title</th>
          <th width="15%">Events</th>
          <th width="35%">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @apps.each do |app| %>
          <tr>
            <td><%= link_to app.name, registered_application_path(app) %></td>
            <td><%= app.events.count %></td>
            <td>
              <%= link_to "Unregister", registered_application_path(app), class: 'btn btn-danger btn-xs', method: :delete, data: {confirm: "Are you sure you want to unregsiter this app?"} %>
              <%= link_to "Edit", edit_registered_application_path(app), class: 'btn btn-primary btn-xs' %>
             </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/registered_applications/new.html.erb
<div class="container">
  <div class="col-md-3"> </div>
  <div class="col-md-6">
    <h1>New App</h1>
    <%= render partial: 'form', locals: {app: @app, cancel_path: registered_applications_path} %>
  </div>
</div>

app/views/registered_applications/show.html.erb
<h1><%= @app.name %></h1>

<div class="row">
  <div class="col-md-4">
    <h4><%= @user.username %></h4>
    <h5><%= link_to @app.url, @app.url %></h5>
    <%= link_to "Unregister", registered_application_path(@app), class: 'btn btn-danger', method: :delete, data: {confirm: "Are you sure you want to unregsiter this app?"} %>
    <%= link_to "Edit", edit_registered_application_path(@app), class: 'btn btn-primary' %>
  </div>
  <div class="col-md-8">
    <table class="table table-hovers">
      <thead>
        <tr>
          <th width="75%">Event Type</th>
          <th width="25%">#</th>
        </tr>
      </thead>
      <tbody>
        <% event_summary(@app.events).each do |event, count| %>
          <tr>
            <td><%= event %></td>
            <td><%= count %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= pie_chart @app.events.group(:name).count %>
    <%= line_chart @app.events.group_by_day(:created_at).count %>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="container">
  <br>
  <br>
  <div class="jumbotron">
    <h1>Welcome to Blocmetrics</h1>
  </div>
</div>